#!/usr/bin/env ruby

require 'optparse'
require_relative 'src/quiz_runner'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: quiz [options]"

  opts.on("--file=MANDATORY", "File to use for quiz") do |v|
    options[:file] = v
  end
end.parse!

module Quiz
  class ExecutorException < StandardError
  end

  class Executor
    def initialize(file)
      @file = file

      unless @file
        raise ExecutorException.new(":file is required")
      end
    end

    def perform
      QuizRunner.new(@file).run
    end
  end
end

quiz = Quiz::Executor.new(options[:file])
quiz.perform
